# Generated by Django 6.1 on 2026-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_personalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
