# Generated by Django 5.2.17 on 2026-09-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_product_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
	migrations.RenameField(
            model_name='personalexpense',
            old_name='expense',
            new_name='amount',
        ),
	migrations.RenameModel(
            old_name='ExpenseCategory',
            new_name='Supplier',
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        
        migrations.AddField(
            model_name='personalexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.personalexpensecategory'),
        ),
        
        migrations.RenameModel(
                    old_name='FirmExpense',
                    new_name='SupplierPayment',
                ),
    ]
