# Generated by Django 5.2.17 on 2026-09-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_personalexpensecategory_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='expense',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='category',
            new_name='supplier',
        ),
    ]
