# Generated by Django 6.1.1 on 2026-09-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_rename_expense_supplierpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalexpensecategory',
            options={'verbose_name': 'Personal expense category', 'verbose_name_plural': 'Personal expense categories'},
        ),
    ]
