# Generated by Django 6.1.1 on 2026-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_personalexpensecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'QR')], max_length=100, null=True),
        ),
    ]
