# Generated by Django 6.1.1 on 2026-10-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_sale_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card', 'card'), ('qr', 'qr')], max_length=100, null=True),
        ),
    ]
