# Generated by Django 5.2.17 on 2026-10-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_sale_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('add', 'Add'), ('remove', 'Remove'), ('adjust', 'Adjust')], max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
