# Generated by Django 5.2.17 on 2026-10-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_inventory_delete_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='mode',
        ),
    ]
