# Generated by Django 5.2.17 on 2026-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_rename_type_inventory_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card', 'card'), ('qr', 'qr'), ('p2p', 'p2p')], default='cash', max_length=100, null=True),
        ),
    ]
